apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: web
  ports:
  - name: http
    port: 38080
    targetPort: 8080
  - name: https
    port: 38443
    targetPort: 8443
