apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-tool
spec:
  selector:
    app: nginx-tool
  ports:
  - name: http-nginx
    port: 9001
    targetPort: 80
  - name: http-multitool
    port: 9002
    targetPort: 8080
