apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: nginx-multitool
spec:
  selector:
    matchLabels:
      app: network-multitool
  template:
    metadata:
      labels:
        app: network-multitool
    spec:
      # hostNetwork: true
      # tolerations:
      # - operator: Exists
      #   effect: NoSchedule
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
      - name: nginx
        image: nginx:latest
        # resources:
        #   requests:
        #     cpu: "1m"
        #     memory: "20Mi"
        #   limits:
        #     cpu: "10m"
        #     memory: "20Mi"
        # securityContext:
        #   runAsUser: 0
        #   capabilities:
        #     add: ["NET_ADMIN"]